
name: bbr_internals

# --------------------------------------------------
common_parameters:
  send_duration: 1.0 #s
  truncate_front: 0 #s
  truncate_back: 0 #s
  plot_load_resolution: 0.01

# --------------------------------------------------
varying_parameters:
  senders: [1]
  link_capacity: [100] # Mbps
  switch_buffer: [0.5] # expressed in BDP of link l
  cc_combination:
    - ['BBR']
  link_latency: [10] # In ms
  source_latency_range: 
    - [5.0, 10.0]
  qdisc:
    - Drop-tail

# -------------------------------------------------
model_parameters:
  computation_parameters:
    stp: 0.01 #ms
  trace_parameters:
    plot_trace: True
    background_parameters:
      - senders
      - link_capacity
      - link_latency
      - switch_buffer
      - cc_combination
      - source_latency_range
    foreground_parameters:
      - qdisc
    rate_not_cwnd: True
  analysis_parameters:
    analyze: True

# --------------------------------------------------
experiment_parameters:
  pox_directory: [/home/simon/prog/pox/, /home/simonsch/pox/]
  base_config: mininet_experiments/base_config.yaml
  runs: 1

# --------------------------------------------------

emulab_parameters:
  base_config: emulab_experiments/base_config.yaml

# --------------------------------------------------
plots: []

trace_plots:

  bbr_internals:
    model_results: True
    experiment_results: True
    metrics: [x_0, xdel_0, xbtl_0, xmax_0]
    paper_version: True
    legend: True
    legend_bottom: False
    focus: True
    legend_keys:
      x_0: $x_i$ 
      xbtl_0: $x_i^{\mathrm{btl}}$
      xmax_0: $x_i^{\mathrm{max}}$
      xdel_0: $x_i^{\mathrm{dlv}}$
      w_0: $w_i$
    other:
      senders: 1
      qdisc: Drop-tail
      cc_combination: BBR
      link_latency: 10
      switch_buffer: 0.5
      source_latency_range: [5.0, 10.0]
