name: bbr_debug

# --------------------------------------------------
common_parameters:
  send_duration: 30.0 #s
  truncate_front: 21.0 #s
  truncate_back: 0.0 #s
  plot_load_resolution: 0.01

# --------------------------------------------------
varying_parameters:
  senders: [10]
  link_capacity: [100] # Mbps
  switch_buffer: [0.5, 1.0, 1.5, 2.0] # expressed in BDP of link l
  cc_combination:
    - ['BBR']
    #- ['RENO', 'BBR']
    #- ['RENO', 'BBR2']
    #- ['CUBIC', 'BBR2']
  link_latency: [10] # In ms
  source_latency_range: 
    - [5.0, 10.0]
  qdisc:
    - Drop-tail

# -------------------------------------------------
model_parameters:
  computation_parameters:
    stp: 0.01 #ms
  trace_parameters:
    plot_trace: True
    background_parameters:
      - senders
      - link_capacity
      - link_latency
      - switch_buffer
      - cc_combination
      - source_latency_range
    foreground_parameters:
      - qdisc
    rate_not_cwnd: True
  analysis_parameters:
    analyze: True

# --------------------------------------------------
experiment_parameters:
  pox_directory: [/home/simon/prog/pox/, /home/simonsch/pox/]
  base_config: mininet_experiments/base_config.yaml
  runs: 3
  delete_raw_dump: true

# --------------------------------------------------
plots: []

trace_plots:

  trace_droptail:
    model_results: True
    experiment_results: False
    metrics: [x_0, v_1, w_1, mifl_1, x_1, xdel_1, q]
    smoothed_metrics: [x_1]
    paper_version: True
    legend: True
    legend_bottom: False
    y_limit: 250
    legend_keys:
      y: y
    other:
      senders: 2
      qdisc: Drop-tail
      cc_combination: RENO/BBR
      switch_buffer: 5.0
      source_latency_range: [5.0, 10.0]

  trace_10:
    model_results: True
    experiment_results: True
    #metrics: [mifl_0, mifl_1, mifl_2, mifl_3, mifl_4, mifl_5, mifl_6, mifl_7, mifl_8, mifl_9]
    metrics: [x_0, x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9]
    #metrics: [x_1, xdel_1, x_2, xdel_2]
    #metrics: [x_9, mifl_9, mup_9, v_9, wlo_9, whi_9, tstr_9, xbtl_9, xmax_9]
    smoothed_metrics: [x_0, x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9, xdel_2]
    paper_version: True
    legend: True
    legend_bottom: False
    focus: True
    y_limit: 30
    legend_keys:
      x_0: $x_0$
    other:
      senders: 10
      qdisc: Drop-tail
      cc_combination: BBR
      switch_buffer: 1.0
      source_latency_range: [5.0, 10.0]


