name: c_reno

# --------------------------------------------------
common_parameters:
  send_duration:  20 #s
  truncate_front: 10 #s
  truncate_back:  0 #s

# --------------------------------------------------
varying_parameters:
  senders: [2]
  link_capacity: [50,100,200,500,750,1000] # Mbps
  switch_buffer: [0.5] # expressed in BDP of link l
  cc_combination:
    - ['RENO']
  link_latency: [2.5] # In ms
  source_latency_range: 
    - [2.0, 2.0]
  qdisc:
    - Drop-tail

# -------------------------------------------------
model_parameters:
  computation_parameters:
    stp: 0.01 #ms
  trace_parameters:
    plot_trace: True
    background_parameters:
      - senders
      - link_capacity
      - link_latency
      - switch_buffer
      - cc_combination
      - source_latency_range
    foreground_parameters:
      - qdisc
    rate_not_cwnd: True
  analysis_parameters:
    analyze: True

# --------------------------------------------------
experiment_parameters:
  pox_directory: [/home/simon/prog/pox, /home/simonsch/pox/]
  base_config: mininet_experiments/base_config.yaml
  runs: 3

# --------------------------------------------------

emulab_parameters:
  base_config: emulab_experiments/base_config.yaml

# --------------------------------------------------
plots:

  A_loss_capacity_droptail:
    model_results: False
    experiment_results: True
    legend: False
    x: link_capacity
    y: loss
    z: cc_combination
    other:
      senders: 2
      #link_latency: 2.5
      qdisc: Drop-tail
      source_latency_range: [2.0, 2.0]

  B_utilization_capacity_droptail:
    model_results: False
    experiment_results: True
    legend: False
    x: link_capacity
    y: utilization
    z: cc_combination
    other:
      senders: 2
      #link_latency: 2.5
      qdisc: Drop-tail
      source_latency_range: [2.0, 2.0]

  C_queue_capacity_droptail:
    model_results: False
    experiment_results: True
    legend: False
    x: link_capacity
    y: avg_queue
    z: cc_combination
    other:
      senders: 2
      #link_latency: 2.5
      qdisc: Drop-tail
      source_latency_range: [2.0, 2.0]